Functionnal Copper client
trakx/copper-api-client pull request #1
Opened 2020-12-03 14:34 UTC by AymericNoel

2020-12-03 16:00 UTC, AymericNoel commented
I'm on the cleanup of the OpenApi on swaggerHub. This one is not clean enough...

But we have all of the config yet !

2020-12-04 08:02 UTC, monsieurleberre approved these changes, later dismissed
![Awesome](https://media.giphy.com/media/KfqdYiISwUsFaCgd7G/giphy.gif)
Booom 💥💥

2020-12-04 08:02 UTC, monsieurleberre commented on src/Trakx.Copper.ApiClient.Tests/Secret.cs
> +        public static string? ExchangeApiKey => Environment.GetEnvironmentVariable("CopperApiConfiguration__ApiKey");
On these new projects, let's make sure we try not to accumulate warnings like this one (you can use `!`)

2020-12-04 17:26 UTC, AymericNoel commented
Codacy told that we should remove partial from classes but it don"t see that these classes are also in ApiClient so the partial isn't gratuitous ... no?

2020-12-22 08:30 UTC, monsieurleberre requested changes
Excellent! Thanks 🦾🦾💥

2020-12-22 08:30 UTC, monsieurleberre commented on src/Trakx.Copper.ApiClient.Tests/Integration/AccountsClientTests.cs
> +        [Fact(Skip = "should have api keys and accounts")]
haha I got some yesterday!

2020-12-22 08:30 UTC, monsieurleberre commented on src/Trakx.Copper.ApiClient/ClientConfigurator.cs
>              switch (clientType.Name)
let's remove that switch maybe?

2020-12-22 08:31 UTC, monsieurleberre approved these changes

2020-12-22 08:38 UTC, merged